
name: python_cache
version: 0.0.1
language: python
description: "本插件主要缓存 `pip install`的包"
public: true
tags:
  - python
  - cache
inputs:
  - name: FLOW_ENABLE_CACHE
    editable: true
    options:
      - TRUE=true
      - FALSE=false
  - name: FLOW_VERSION
    editable: false
  - name: FLOW_PROJECT_ID
    editable: false
outputs:
  - name: FLOW_ENABLE_CACHE
script_path: ./run.sh  
  
template: |  
  
  
